/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BBtn: typeof import('./components/common/BBtn.vue')['default']
    BField: typeof import('./components/common/BField.vue')['default']
    BRadio: typeof import('./components/common/BRadio.vue')['default']
    BRadioGroup: typeof import('./components/common/BRadioGroup.vue')['default']
    BStepper: typeof import('./components/common/BStepper.vue')['default']
  }
}
